export enum UserRole {
  ADMIN = 'ADMIN',
  DIRECTOR = 'DIRECTOR',
  BRANCH_DIRECTOR = 'BRANCH_DIRECTOR',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
}

export enum StaffPosition {
  ED_DIRECTOR = 'ED_DIRECTOR',
  LEAD_TEACHER = 'LEAD_TEACHER',
  ASSISTANT_TEACHER = 'ASSISTANT_TEACHER',
  PARAPROFESSIONAL = 'PARAPROFESSIONAL',
}

export enum RenewalPeriod {
  NONE = 'NONE',
  ANNUAL = 'ANNUAL',
  BIENNIAL = 'BIENNIAL',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum EmploymentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ON_LEAVE = 'ON_LEAVE',
  TERMINATED = 'TERMINATED',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}
